//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.832.
// 
namespace ce5b.newsint.ad.ni.sapr3d {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Z_PM_GET_STORAGE_LOCBinding", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_PM_GET_STORAGE_LOCService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Z_PM_GET_STORAGE_LOCService() {
            this.Url = "http://sapr3t.ni.ad.newsint/sap/bc/soap/rfc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sap.com/Z_PM_GET_STORAGE_LOC", RequestNamespace="urn:sap-com:document:sap:rfc:functions", ResponseElementName="Z_PM_GET_STORAGE_LOC.Response", ResponseNamespace="urn:sap-com:document:sap:rfc:functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Z_PM_GET_STORAGE_LOC([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PLANT, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] ref ZHANDHELD_LOC[] RETURN) {
            object[] results = this.Invoke("Z_PM_GET_STORAGE_LOC", new object[] {
                        PLANT,
                        RETURN});
            RETURN = ((ZHANDHELD_LOC[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginZ_PM_GET_STORAGE_LOC(string PLANT, ZHANDHELD_LOC[] RETURN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Z_PM_GET_STORAGE_LOC", new object[] {
                        PLANT,
                        RETURN}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndZ_PM_GET_STORAGE_LOC(System.IAsyncResult asyncResult, out ZHANDHELD_LOC[] RETURN) {
            object[] results = this.EndInvoke(asyncResult);
            RETURN = ((ZHANDHELD_LOC[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZHANDHELD_LOC {
        
        private string pLANTField;
        
        private string sTOR_LOCField;
        
        private string pLANT_TXTField;
        
        private string lOC_TXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PLANT {
            get {
                return this.pLANTField;
            }
            set {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STOR_LOC {
            get {
                return this.sTOR_LOCField;
            }
            set {
                this.sTOR_LOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PLANT_TXT {
            get {
                return this.pLANT_TXTField;
            }
            set {
                this.pLANT_TXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOC_TXT {
            get {
                return this.lOC_TXTField;
            }
            set {
                this.lOC_TXTField = value;
            }
        }
    }
}
